name: a
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

# resolution: workspace

dependencies:
  build: ^2.4.2
  source_gen: ^1.5.0
  dart_style: ^2.3.8
  glob: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.15

